apiVersion: apps/v1
kind: Deployment
metadata:
  name: prac7p-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prac7p-app
  template:
    metadata:
      labels:
        app: prac7p-app
    spec:
      containers:
        - name: prac7p-app
          image: srii0305/prac7p-app
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: mongodb://admin:pass123@mongo-service:27017/?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: prac7p-service
spec:
  selector:
    app: prac7p-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer